global:
route:
  #group_by: ['instance', 'severity']
  group_by: ['emample']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'telegram'

receivers:
- name: 'telegram'
  webhook_configs:
  - send_resolved: True
    url: http://prometheus-bot:9087/alert/509736774